warning off;
lambda = 1;
lens = [1 2 3 4 6 8 12 24];
individ_syls = {'b','B','d','D','t','T','k','K','l','L','g', ...
        'G','p','P','v','V','z','Z','#'};
syls = 'bBdDtTkKlLgGpPvVzZ#';

for len = 1:8
  fprintf('calculating len=%d\n',lens(len));
  for file = 1:10
    [tps{len}{file} mis{len}{file} stps{len}{file}] = ...
      findCounts(sents{len}{file},syls,lambda);
    
    [tp_s(:,len,file) tp_t(:,len,file) tp_d(:,len,file)] = ...
      multiMeasureModel(tps{len}{file},corr{len}{file},...
      incorr{len}{file},syls);
    [tps_s(:,len,file) tps_t(:,len,file) tps_d(:,len,file)] = ...
      multiMeasureModel(stps{len}{file},corr{len}{file},...
      incorr{len}{file},syls);
    [mi_s(:,len,file) mi_t(:,len,file) mi_d(:,len,file)] = ...
      multiMeasureModel(mis{len}{file},corr{len}{file},...
      incorr{len}{file},syls);  
  end
end
warning on;